### ISSUE TITLE
Hangs on splash screen if denied audio recording

### ISSUE THREAD

**Issue by JKingweb** [iamSahdeep/Bop#25]
**Describe the bug**
Hangs on splash screen unless audio recording permission is granted.

**To Reproduce**
1. Start the software for the first time
2. Grant access to files
3. Deny access to microphone
4. Experience hang

**Expected behavior**
The application should work without access to the microphone.

**Smartphone (please complete the following information):**
 - OnePlus 3
 - Android 8.1 (LineageOS 15.1)
 - F-Droid build 1.1.1

**Additional context**
If blocked via Privacy Guard, the application crashes.

**Comment by iamSahdeep** [comment]
Microphone permission is required for visualizers in musicplayer. It won't work if you don't allow it. As you are saying it hangs/stops at splash screen, It is because i am not allowing user to get in unless both permissions are given. ^_^

I can make it, to work without visualizers but then i need to make tons of changes in code.
What would you suggest? 

And for Privacy Guard, I am not sure about it. Crash might occur because PG is not allowing app to access Permission Manager within application. Don't know much about it.

**Comment by arschficken** [comment]
Just encountered this same issue. At the very least I would suggest putting an explanation of why the app requests permission to record audio. This should appear before the app makes the request, and also afterwards if it is denied. Showing a non-functional orange screen just makes it look like the app is broken.

Open source users are pretty savvy, so you can expect many of them to deny a seemingly incongruous request such as a music _player_ asking to _record_. Even knowing the reason, I won't give the app permission to do that, not least because I prefer to enjoy music without visualisation.

Judging by the screenshots it's a very promising app though!

**Comment by iamSahdeep** [comment]
Surely i will work on it, would take some time, probabaly in next major release.

**Comment by iamSahdeep** [comment]
hey @JKingweb and @arschficken i have made the Microphone usage optional. you can now use it without giving Recording Permission but yes without visualizers. You can test the debuggable apk now  an help me is the application is not working as expected. Here is the 
 apk stored : https://github.com/iamSahdeep/Bop/blob/master/buildApk/app-debug.apk
Or can wait for the next release which is coming soon. :100:

**Comment by JKingweb** [comment]
Works great! Thanks!
